import subprocess
path_drive = '/content/drive/MyDrive/projeto_final_BI'

subprocess.run(["python", "./cargas_dw/create_dw.py"], check=True)
subprocess.run(["python", "./cargas_dw/carga_manual_circobito.py"], check=True)
subprocess.run(["python", "./cargas_dw/carga_manual_escfal.py"], check=True)
subprocess.run(["python", "./cargas_dw/carga_manual_estcivil.py"], check=True)
subprocess.run(["python", "./cargas_dw/carga_manual_racacor.py"], check=True)
subprocess.run(["python", "./cargas_dw/carga_manual_sexo.py"], check=True)
subprocess.run(["python", "./cargas_dw/carga_manual_tplocor.py"], check=True)
subprocess.run(["python", "./cargas_dw/carga_merge_cids.py", "./cargas_dw/cid.json"], check=True)
subprocess.run(["python", "./cargas_dw/carga_merge_municipios.py", "./cargas_dw/Municipios_IBGE.csv", "./cargas_dw/municipios.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_populacao.py", "./cargas_dw/estimativa_dou_2018.xls"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_populacao.py", "./cargas_dw/estimativa_dou_2019.xls"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_populacao.py", "./cargas_dw/estimativa_dou_2020.xls"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_populacao.py", "./cargas_dw/estimativa_dou_2021.xls"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_populacao.py", "./cargas_dw/estimativa_dou_2022.xls"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_populacao.py", "./cargas_dw/estimativa_dou_2024.xls"], check=True)
subprocess.run(["python", "./cargas_dw/carga_merge_ocupacao.py", "./cargas_dw/cbo2002-ocupacao.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_obito.py", "./cargas_dw/Mortalidade_Geral_2018.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_obito.py", "./cargas_dw/Mortalidade_Geral_2019.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_obito.py", "./cargas_dw/Mortalidade_Geral_2020.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_obito.py", "./cargas_dw/Mortalidade_Geral_2021.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_obito.py", "./cargas_dw/Mortalidade_Geral_2022.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_obito.py", "./cargas_dw/Mortalidade_Geral_2023.csv"], check=True)
subprocess.run(["python", "./cargas_dw/carga_incremental_obito.py", "./cargas_dw/Mortalidade_Geral_2024.csv"], check=True)
