# -*- coding: utf-8 -*-
"""carga_final.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gF791HKRYJZWe-Y7fd0xfQOOKRKkiXqX
"""

import subprocess
path_drive = '/content/drive/MyDrive/projeto_final_BI'

subprocess.run(["python", "create_dw.py"], check=True)
subprocess.run(["python", "carga_manual_circobito.py"], check=True)
subprocess.run(["python", "carga_manual_escfal.py"], check=True)
subprocess.run(["python", "carga_manual_estcivil.py"], check=True)
subprocess.run(["python", "carga_manual_racacor.py"], check=True)
subprocess.run(["python", "carga_manual_sexo.py"], check=True)
subprocess.run(["python", "carga_manual_tplocor.py"], check=True)
subprocess.run(["python", "carga_merge_cids.py", "./cid.json"], check=True)
subprocess.run(["python", "carga_merge_municipios.py"], check=True)
subprocess.run(["python", "carga_merge_ocupacao.py", "./cbo2002-ocupacao.csv"], check=True)
subprocess.run(["python", "carga_full_obito.py", "./Mortalidade_Geral_2018.csv"], check=True)
subprocess.run(["python", "carga_full_obito.py", "./Mortalidade_Geral_2019.csv"], check=True)
subprocess.run(["python", "carga_full_obito.py", "./Mortalidade_Geral_2020.csv"], check=True)
subprocess.run(["python", "carga_full_obito.py", "./Mortalidade_Geral_2021.csv"], check=True)
subprocess.run(["python", "carga_full_obito.py", "./Mortalidade_Geral_2022.csv"], check=True)
subprocess.run(["python", "carga_full_obito.py", "./Mortalidade_Geral_2023.csv"], check=True)
subprocess.run(["python", "carga_full_obito.py", "./Mortalidade_Geral_2024.csv"], check=True)