import sqlite3

conn = sqlite3.connect("DW.db")
cur = conn.cursor()
cur.execute("PRAGMA foreign_keys = ON;")

ddl = [
"""
	CREATE TABLE IF NOT EXISTS "DWCD_TPLOCOR" (
    "SK_TPLOCOR" INTEGER NOT NULL UNIQUE,
    "CD_TPLOCOR" INTEGER NOT NULL,
    "DS_TPLOCOR" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_TPLOCOR")
);
""",
"""
  CREATE TABLE IF NOT EXISTS "DWCD_CIRCOBITO" (
	"SK_CIRCOBITO" INTEGER NOT NULL UNIQUE,
  "CD_CIRCOBITO" INTEGER NOT NULL UNIQUE,
	"DS_CIRCOBITO" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_CIRCOBITO")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_RACACOR" (
	"SK_RACACOR" INTEGER NOT NULL UNIQUE,
	"DS_RACACOR" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_RACACOR")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_SEXO" (
	"SK_SEXO" INTEGER NOT NULL UNIQUE,
	"CD_SEXO" INTEGER NOT NULL,
	"DS_SEXO" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_SEXO")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_ESCFAL" (
	"SK_ESCFAL" INTEGER NOT NULL UNIQUE,
	"CD_ESCFAL" INTEGER NOT NULL,
	"DS_ESCFAL" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_ESCFAL")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_ESTCIV" (
	"SK_ESTCIV" INTEGER NOT NULL UNIQUE,
	"CD_ESTCIV" INTEGER NOT NULL,
	"DS_ESTCIV" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_ESTCIV")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_REGIAO" (
	"SK_REGIAO" INTEGER NOT NULL UNIQUE,
	"CD_REGIAO" INTEGER NOT NULL,
	"NM_REGIAO" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_REGIAO")
);
""",

"""
  CREATE TABLE IF NOT EXISTS "DWCD_ESTADO" (
	"SK_ESTADO" INTEGER NOT NULL UNIQUE,
	"CD_ESTADO" INTEGER NOT NULL,
	"NM_ESTADO" VARCHAR NOT NULL,
	"SK_REGIAO" INTEGER NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_ESTADO"),
	FOREIGN KEY ("SK_REGIAO") REFERENCES "DWCD_REGIAO"("SK_REGIAO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",

"""
  CREATE TABLE IF NOT EXISTS "DWCD_MUNICIPO" (
	"SK_MUNICIPIO" INTEGER NOT NULL UNIQUE,
	"CD_MUNICIPIO" INTEGER NOT NULL,
	"SK_ESTADO" INTEGER NOT NULL,
	"NM_MUNICIPIO" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_MUNICIPIO"),
	FOREIGN KEY ("SK_ESTADO") REFERENCES "DWCD_ESTADO"("SK_ESTADO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",    

"""
  CREATE TABLE IF NOT EXISTS "DWCD_PESSOA" (
	"SK_PESSOA" INTEGER NOT NULL UNIQUE,
	"SK_SEXO" INTEGER NOT NULL,
	"SK_RACACOR" INTEGER NOT NULL,
	"SK_ESCFAL" INTEGER NOT NULL,
	"SK_ESTCIV" INTEGER NOT NULL,
	"SK_MUNICIPIO" INTEGER NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_PESSOA"),
    FOREIGN KEY ("SK_SEXO") REFERENCES "DWCD_SEXO"("SK_SEXO")
	FOREIGN KEY ("SK_RACACOR") REFERENCES "DWCD_RACACOR"("SK_RACACOR")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  	FOREIGN KEY ("SK_ESCFAL") REFERENCES "DWCD_ESCFAL"("SK_ESCFAL")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  	FOREIGN KEY ("SK_ESTCIV") REFERENCES "DWCD_ESTCIV"("SK_ESTCIV")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  	FOREIGN KEY ("SK_MUNICIPIO") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
                
"""
	CREATE TABLE IF NOT EXISTS "DWCD_CIDS" (
	"SK_CID" INTEGER NOT NULL UNIQUE,
	"CD_CID" INTEGER NOT NULL,
	"DS_CID" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_CAUSAOBITO" (
	"SK_CAUSAOBITO" INTEGER NOT NULL UNIQUE,
	"SK_CAUSABAS" INTEGER NOT NULL,
	"SK_LINHAA" INTEGER NOT NULL,
	"SK_LINHAB" INTEGER NOT NULL,
	"SK_LINHAC" INTEGER NOT NULL,
	"SK_LINHAD" INTEGER NOT NULL,
	"SK_LINHAII" INTEGER NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_CAUSAOBITO"),
	FOREIGN KEY ("SK_CAUSABAS") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_LINHAA") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_LINHAB") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_LINHAC") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_LINHAD") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_LINHAII") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
				    
"""
  CREATE TABLE IF NOT EXISTS "DWMV_OBITO" (
	"SK_OBITO" INTEGER NOT NULL UNIQUE,
	"SK_MUNICIPIO" INTEGER NOT NULL,
	"SK_CAUSAOBITO" INTEGER NOT NULL,
	"SK_PESSOA" INTEGER NOT NULL,
	"SK_CIRCOBITO" INTEGER NOT NULL,
    "ST_ACIDTRAB" INTEGER DEFAULT 0,
	"ST_FETAL" BOOLEAN NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_OBITO"),
	FOREIGN KEY ("SK_MUNICIPIO") REFERENCES "DWCD_MUNICIPO"("SK_MUNICIPIO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("SK_CIRCOBITO") REFERENCES "DWCD_CIRCOBITO"("SK_CIRCOBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  	FOREIGN KEY ("SK_PESSOA") REFERENCES "DWCD_PESSOA"("SK_PESSOA")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  	FOREIGN KEY ("SK_CAUSAOBITO") REFERENCES "DWCD_CAUSAOBITO"("SK_CAUSAOBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
"""
]


for stmt in ddl:
    cur.execute(stmt)

conn.commit()
conn.close()