import sqlite3

conn = sqlite3.connect("DW.db")
cur = conn.cursor()
cur.execute("PRAGMA foreign_keys = ON;")

ddl = [
"""
	CREATE TABLE IF NOT EXISTS "DWCD_TIPOBTOCOR" (
	"SK_TIPOBTOCOR" INTEGER NOT NULL UNIQUE,
	"CD_TIPOBTOCOR" INTEGER NOT NULL,
	"DS_TIPO" VARCHAR,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_TIPOBTOCOR")
);
""",
"""
  CREATE TABLE IF NOT EXISTS "DWCD_CIRCOBITO" (
	"SK_CIRCOBITO" INTEGER NOT NULL UNIQUE,
  "CD_CIRCOBITO" INTEGER NOT NULL UNIQUE,
	"DS_CIRCOBITO" VARCHAR NOT NULL,
	"ST_ACIDTRAB" INTEGER NOT NULL,
	"CD_TIPOBTOCOR" INTEGER NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_CIRCOBITO"),
  FOREIGN KEY ("CD_TIPOBTOCOR") REFERENCES "DWCD_TIPOBTOCOR"("SK_TIPOBTOCOR")
  ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_RACACOR" (
	"SK_RACACOR" INTEGER NOT NULL UNIQUE,
	"DS_RACACOR" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_RACACOR")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_SEXO" (
	"SK_SEXO" INTEGER NOT NULL UNIQUE,
	"CD_SEXO" INTEGER NOT NULL,
	"DS_SEXO" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_SEXO")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_ESCFAL" (
	"SK_ESCFAL" INTEGER NOT NULL UNIQUE,
	"CD_ESCFAL" INTEGER NOT NULL,
	"DS_ESCFAL" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_ESCFAL")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_ESTCIV" (
	"SK_ESTCIV" INTEGER NOT NULL UNIQUE,
	"CD_ESTCIV" INTEGER NOT NULL,
	"DS_ESTCIV" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_ESTCIV")
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_REGIAO" (
	"SK_REGIAO" INTEGER NOT NULL UNIQUE,
	"CD_REGIAO" INTEGER NOT NULL,
	"NM_REGIAO" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_REGIAO")
);
""",

"""
  CREATE TABLE IF NOT EXISTS "DWCD_ESTADO" (
	"SK_ESTADO" INTEGER NOT NULL UNIQUE,
	"CD_ESTADO" INTEGER NOT NULL,
	"NM_ESTADO" VARCHAR NOT NULL,
	"CD_REGIAO" INTEGER NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_ESTADO"),
	FOREIGN KEY ("CD_REGIAO") REFERENCES "DWCD_REGIAO"("SK_REGIAO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",

"""
  CREATE TABLE IF NOT EXISTS "DWCD_MUNICIPO" (
	"SK_MUNICIPIO" INTEGER NOT NULL UNIQUE,
	"CD_MUNICIPIO" INTEGER NOT NULL,
	"CD_ESTADO" INTEGER NOT NULL,
	"NM_MUNICIPIO" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_MUNICIPIO"),
	FOREIGN KEY ("CD_ESTADO") REFERENCES "DWCD_ESTADO"("SK_ESTADO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",    

"""
  CREATE TABLE IF NOT EXISTS "DWCD_PESSOA" (
	"SK_PESSOA" INTEGER NOT NULL UNIQUE,
	"CD_PESSOA" INTEGER NOT NULL,
	"CD_SEXO" INTEGER NOT NULL,
	"CD_RACACOR" INTEGER NOT NULL,
	"CD_ESCFAL" INTEGER NOT NULL,
	"CD_ESTCIV" INTEGER NOT NULL,
	"CD_MUNICIPIO" INTEGER NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_PESSOA"),
	FOREIGN KEY ("CD_RACACOR") REFERENCES "DWCD_RACACOR"("SK_RACACOR")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("CD_ESCFAL") REFERENCES "DWCD_ESCFAL"("SK_ESCFAL")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("CD_ESTCIV") REFERENCES "DWCD_ESTCIV"("SK_ESTCIV")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("CD_MUNICIPIO") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
                
"""
	CREATE TABLE IF NOT EXISTS "DWCD_CIDS" (
	"SK_CID" INTEGER NOT NULL UNIQUE,
	"CD_CID" INTEGER NOT NULL,
	"DS_CID" VARCHAR NOT NULL,
	"DT_CARGA" DATETIME NOT NULL
);
""",
        
"""
	CREATE TABLE IF NOT EXISTS "DWCD_CAUSAOBITO" (
	"SK_CAUSAOBITO" INTEGER NOT NULL UNIQUE,
	"CD_CAUSABAS" INTEGER NOT NULL,
	"CD_LINHAA" INTEGER NOT NULL,
	"CD_LINHAB" INTEGER NOT NULL,
	"CD_LINHAC" INTEGER NOT NULL,
	"CD_LINHAD" INTEGER NOT NULL,
	"CD_LINHAII" INTEGER NOT NULL,
	"DT_CARGA" DATETIME NOT NULL,
	PRIMARY KEY("SK_CAUSAOBITO"),
	FOREIGN KEY ("CD_CAUSABAS") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD_LINHAA") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD_LINHAB") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD_LINHAC") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD_LINHAD") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD_LINHAII") REFERENCES "DWCD_CIDS"("SK_CID")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
				    
"""
  CREATE TABLE IF NOT EXISTS "DWMV_OBITO" (
	"SK_OBITO" INTEGER NOT NULL UNIQUE,
	"CD_MUNICIPIO" INTEGER NOT NULL,
	"CD_CAUSAOBITO" INTEGER NOT NULL,
	"CD_PESSOA" INTEGER NOT NULL,
	"CD_CIRCOBITO" INTEGER NOT NULL,
	"ST_FETAL" BOOLEAN NOT NULL,
	"DT_CARGA" DATETIME,
	PRIMARY KEY("SK_OBITO"),
	FOREIGN KEY ("CD_MUNICIPIO") REFERENCES "DWCD_MUNICIPO"("SK_MUNICIPIO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
	FOREIGN KEY ("CD_CIRCOBITO") REFERENCES "DWCD_CIRCOBITO"("SK_CIRCOBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("CD_PESSOA") REFERENCES "DWCD_PESSOA"("SK_PESSOA")
	ON UPDATE NO ACTION ON DELETE NO ACTION,
  FOREIGN KEY ("CD_CAUSAOBITO") REFERENCES "DWCD_CAUSAOBITO"("SK_CAUSAOBITO")
	ON UPDATE NO ACTION ON DELETE NO ACTION
);
"""
]


for stmt in ddl:
    cur.execute(stmt)

conn.commit()
conn.close()