import sqlite3

conn = sqlite3.connect("DW.db")
cur = conn.cursor()
ddl = [
"""
CREATE TABLE IF NOT EXISTS "DWCD_REGIAO" (
    "SK_REGIAO" INTEGER NOT NULL UNIQUE,
    "NM_REGIAO" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_REGIAO")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_ESTADO" (
    "SK_ESTADO" INTEGER NOT NULL UNIQUE,
    "CD_ESTADO" INTEGER NOT NULL,
    "NM_ESTADO" VARCHAR NOT NULL,
    "SK_REGIAO" INTEGER NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_ESTADO"),
    FOREIGN KEY ("SK_REGIAO") REFERENCES "DWCD_REGIAO"("SK_REGIAO")
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_MUNICIPIO" (
    "SK_MUNICIPIO" INTEGER NOT NULL UNIQUE,
    "CD_MUNICIPIO" INTEGER NOT NULL,
    "SK_ESTADO" INTEGER NOT NULL,
    "NM_MUNICIPIO" VARCHAR NOT NULL,
    "ST_CAPITAL" BOOLEAN NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_MUNICIPIO"),
    FOREIGN KEY ("SK_ESTADO") REFERENCES "DWCD_ESTADO"("SK_ESTADO")
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWMV_POPULACAO" (
    "SK_MUNICIPIO" INTEGER NOT NULL,
    "ANO" INTEGER NOT NULL,
    "QTD_POPULACAO" INTEGER NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_MUNICIPIO", "ANO"),
    FOREIGN KEY ("SK_MUNICIPIO") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_RACACOR" (
    "SK_RACACOR" INTEGER NOT NULL UNIQUE,
    "CD_RACACOR" INTEGER NOT NULL,
    "DS_RACACOR" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_RACACOR")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_SEXO" (
    "SK_SEXO" INTEGER NOT NULL UNIQUE,
    "CD_SEXO" INTEGER NOT NULL,
    "DS_SEXO" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_SEXO")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_ESCFAL" (
    "SK_ESCFAL" INTEGER NOT NULL UNIQUE,
    "CD_ESCFAL" INTEGER NOT NULL,
    "DS_ESCFAL" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_ESCFAL")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_ESTCIV" (
    "SK_ESTCIV" INTEGER NOT NULL UNIQUE,
    "CD_ESTCIV" INTEGER NOT NULL,
    "DS_ESTCIV" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_ESTCIV")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_OCUP" (
    "SK_OCUP" INTEGER NOT NULL UNIQUE,
    "CD_OCUP" INTEGER NOT NULL,
    "DS_OCUP" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_OCUP")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_CIRCOBITO" (
    "SK_CIRCOBITO" INTEGER NOT NULL UNIQUE,
    "CD_CIRCOBITO" INTEGER NOT NULL,
    "DS_CIRCOBITO" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_CIRCOBITO")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_TPLOCOR" (
    "SK_TPLOCOR" INTEGER NOT NULL UNIQUE,
    "CD_TPLOCOR" INTEGER NOT NULL,
    "DS_TPLOCOR" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_TPLOCOR")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_CIDS" (
    "SK_CID" INTEGER NOT NULL UNIQUE,
    "CD_CID" VARCHAR NOT NULL,
    "CD_CID_LINHA" VARCHAR NOT NULL,
    "CD_CID_CAUSA" VARCHAR NOT NULL,
    "DS_CID" VARCHAR NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_CID")
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_CAUSAOBITO" (
    "SK_CAUSAOBITO" INTEGER NOT NULL UNIQUE,
    "CD_CAUSAOBITO" VARCHAR NOT NULL,
    "SK_CIDBAS" INTEGER NOT NULL,
    "SK_CIDTERM" INTEGER NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    PRIMARY KEY("SK_CAUSAOBITO"),
    FOREIGN KEY ("SK_CIDBAS") REFERENCES "DWCD_CIDS"("SK_CID")
    ON UPDATE NO ACTION ON DELETE NO ACTION
    FOREIGN KEY ("SK_CIDTERM") REFERENCES "DWCD_CIDS"("SK_CID")
    ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWCD_PESSOA" (
    "SK_PESSOA" INTEGER PRIMARY KEY AUTOINCREMENT,
    "CD_PESSOA" VARCHAR NOT NULL,
    "SK_SEXO" INTEGER NOT NULL,
    "SK_RACACOR" INTEGER NOT NULL,
    "SK_ESCFAL" INTEGER NOT NULL,
    "SK_ESTCIV" INTEGER NOT NULL,
    "SK_MUNICIPIO" INTEGER NOT NULL,
    "SK_OCUP" INTEGER NOT NULL,
    "DT_NASC" DATE NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    FOREIGN KEY ("SK_RACACOR") REFERENCES "DWCD_RACACOR"("SK_RACACOR")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_ESTCIV") REFERENCES "DWCD_ESTCIV"("SK_ESTCIV")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_ESCFAL") REFERENCES "DWCD_ESCFAL"("SK_ESCFAL")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_MUNICIPIO") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_OCUP") REFERENCES "DWCD_OCUP"("SK_OCUP")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_SEXO") REFERENCES "DWCD_SEXO"("SK_SEXO")
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
""",
"""
CREATE TABLE IF NOT EXISTS "DWMV_OBITO" (
    "CD_OBITO" INTEGER PRIMARY KEY AUTOINCREMENT,
    "SK_MUNICIPIO" INTEGER NOT NULL,
    "SK_CAUSAOBITO" INTEGER NOT NULL,
    "SK_PESSOA" INTEGER NOT NULL,
    "SK_CIRCOBITO" INTEGER NOT NULL,
    "SK_TPLOCOR" INTEGER NOT NULL,
    "ST_ACIDTRAB" BOOLEAN NOT NULL,
    "ST_FETAL" BOOLEAN NOT NULL,
    "DT_OBITO" DATE NOT NULL,
    "DT_CARGA" DATETIME NOT NULL,
    FOREIGN KEY ("SK_PESSOA") REFERENCES "DWCD_PESSOA"("SK_PESSOA")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_CIRCOBITO") REFERENCES "DWCD_CIRCOBITO"("SK_CIRCOBITO")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_CAUSAOBITO") REFERENCES "DWCD_CAUSAOBITO"("SK_CAUSAOBITO")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_MUNICIPIO") REFERENCES "DWCD_MUNICIPIO"("SK_MUNICIPIO")
        ON UPDATE NO ACTION ON DELETE NO ACTION,
    FOREIGN KEY ("SK_TPLOCOR") REFERENCES "DWCD_TPLOCOR"("SK_TPLOCOR")
        ON UPDATE NO ACTION ON DELETE NO ACTION
);
"""
]
for stmt in ddl:
    cur.execute(stmt)

conn.commit()
conn.close()
